Concatenate output files
phac-nml/staramrnf pull request #14
Opened 2024-06-19 00:50 UTC by sgsutcliffe

Concatenate not just the summary.tsv but all the csv/tsv files.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/staramr/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/staramr _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-06-20 18:27 UTC, sgsutcliffe commented
The issue we had with `CSVTK_CONCAT` nf-core module was that `iridanext-plugin` downstream was classifys all files with `meta.id` tags as being a `sample` but we had been passing a modified `meta.id` to `CSVTK_CONCAT` to properly name the output file. Removing the `meta.id` from the nf-core module fixed this. Due to modification of the module we moved it tp the local directory of `/modules`

2024-06-21 15:29 UTC, apetkau requested changes
This looks really great. Thanks so much Steven 😄 

I have a few comments and suggestions below.

2024-06-21 16:21 UTC, sgsutcliffe commented on modules/local/staramr/main.nf
> +    tuple val(meta), path("*_results/results.xlsx")                     , emit: results_xlsx
Yes, and an extra benefit of this is that I can clean up this code block below:
```
    # Change the names of output files to contain the genome name (allows for CSVTK module to concatenate files downstream)
    mv ${prefix}_results/summary.tsv ${prefix}_results/${prefix}_summary.tsv
    mv ${prefix}_results/detailed_summary.tsv ${prefix}_results/${prefix}_detailed_summary.tsv
    mv ${prefix}_results/resfinder.tsv ${prefix}_results/${prefix}_resfinder.tsv
    mv ${prefix}_results/plasmidfinder.tsv ${prefix}_results/${prefix}_plasmidfinder.tsv
    mv ${prefix}_results/mlst.tsv ${prefix}_results/${prefix}_mlst.tsv
    [[ -f ${prefix}_results/pointfinder.tsv ]] && mv ${prefix}_results/pointfinder.tsv ${prefix}_results/${prefix}_pointfinder.tsv || echo "No pointfinder.tsv"

```
to
```
for f in ${prefix}_results/* ; do mv "\$f" \$(echo \$f | sed 's;/;/${prefix}_;'); done
```

2024-06-21 16:24 UTC, sgsutcliffe commented on modules/local/csvtk/concat/main.nf
> +    tuple path("${prefix}.${out_extension}"), emit: csv
That makes sense, but it is weird that my runs didn't give this error.

2024-06-21 17:55 UTC, sgsutcliffe commented on tests/main.nf.test
> +            assert salmonella_metadata."Predicted Phenotype" == "streptomycin, kanamycin, ampicillin, amoxicillin/clavulanic acid, cefoxitin, ceftriaxone, chloramphenicol, trimethoprim, ciprofloxacin
I think you're right the order wont always be the same. I'll start with the sorted version.

2024-06-25 18:18 UTC, sgsutcliffe commented
The  `nf-test` files for checking `CSVTK_concat` are TSV files with empty columns in some rows (causing Trailing whitespace error) when running `pre-commit run` so I have added an exception for the these files to allow trailing whitespace.

2024-06-25 18:23 UTC, sgsutcliffe commented on workflows/staramr.nf
> +    }.collect().map{
I think this is a great idea. I'd made a note to clean up this code, but with your suggestions I can easily finish it in this PR.

2024-06-28 18:19 UTC, apetkau commented on workflows/staramr.nf
> +    }.collect().map{
Thanks for posting as an issue: https://github.com/phac-nml/staramrnf/issues/16

2024-06-28 18:23 UTC, apetkau approved these changes
This looks great. Thanks so much for all your work on this Steven 😄

2024-06-28 19:10 UTC, merged